## 3. 배열 조작

### 3-1. 배열 인덱싱 및 슬라이싱

In [ ]:
## 기본 인덱싱

arr = np.array([1, 2, 3, 4, 5])
print("Element at index 0:", arr[0])
print("Element at index 4:", arr[4])

In [ ]:
## 다차원 배열 인덱싱

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Element at (0, 0):", arr[0, 0])
print("Element at (1, 2):", arr[1, 2])

In [ ]:
## 배열 슬라이싱

arr = np.array([1, 2, 3, 4, 5])
print("Slice [0:3]:", arr[0:3])
print("Slice [::2]:", arr[::2])

### 3-2. 배열 형상 변경

- **np.reshape()**: 배열의 형상을 변경합니다.
- **np.resize()**: 배열의 크기를 변경합니다.
- **np.ravel()**: 다차원 배열을 1차원으로 펼칩니다.
- **np.flatten()**: 다차원 배열을 1차원으로 펼칩니다.
- **np.append()**: 배열에 요소를 추가합니다.
- **np.insert()**: 배열의 지정한 위치에 요소를 삽입합니다.
- **np.delete()**: 배열의 요소를 삭제합니다.

In [ ]:
arr = np.arange(6)
reshaped_arr = arr.reshape((2, 3))
print("Original Array:", arr)
print("Reshaped Array:\\n", reshaped_arr)

resized_arr = np.resize(arr, (3, 2))
print("Resized Array:\\n", resized_arr)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
ravel_arr = arr.ravel()
flatten_arr = arr.flatten()
print("Ravel Array:", ravel_arr)
print("Flatten Array:", flatten_arr)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
appended_arr = np.append(arr, [6, 7])
inserted_arr = np.insert(arr, 2, 9)
deleted_arr = np.delete(arr, 1)

print("Appended Array:", appended_arr)
print("Inserted Array:", inserted_arr)
print("Deleted Array:", deleted_arr)

### 3-3. 배열 결합 및 분할

- **np.concatenate()**: 두 배열을 결합합니다.
- **np.stack()**: 두 배열을 새로운 축으로 결합합니다.
- **np.hstack()**: 두 배열을 수평으로 결합합니다.
- **np.vstack()**: 두 배열을 수직으로 결합합니다.
- **np.split()**: 배열을 분할합니다.
- **np.hsplit()**: 배열을 수평으로 분할합니다.
- **np.vsplit()**: 배열을 수직으로 분할합니다.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concatenated_arr = np.concatenate((arr1, arr2))
stacked_arr = np.stack((arr1, arr2))
hstacked_arr = np.hstack((arr1, arr2))
vstacked_arr = np.vstack((arr1, arr2))

print("Concatenated Array:", concatenated_arr)
print("Stacked Array:\\n", stacked_arr)
print("Horizontally Stacked Array:", hstacked_arr)
print("Vertically Stacked Array:\\n", vstacked_arr)

In [ ]:
arr = np.arange(9).reshape(3, 3)
split_arr = np.split(arr, 3)
hsplit_arr = np.hsplit(arr, 3)
vsplit_arr = np.vsplit(arr, 3)

print("Split Array:", split_arr)
print("Horizontally Split Array:", hsplit_arr)
print("Vertically Split Array:\\n", vsplit_arr)

## 4. 배열 연산

### 4-1. 기본연산

- **np.add()**: 두 배열의 요소를 더합니다.
- **np.subtract()**: 두 배열의 요소를 뺍니다.
- **np.multiply()**: 두 배열의 요소를 곱합니다.
- **np.divide()**: 두 배열의 요소를 나눕니다.

### 스칼라 + 벡터 연산

$$
\begin{align}
x=
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
\end{align}
$$

$$
\begin{align}
10 - x = 10 -
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
=
\begin{bmatrix}
10 - 1 \\
10 - 2 \\
10 - 3 \\
\end{bmatrix}
=
\begin{bmatrix}
9 \\
8 \\
7 \\
\end{bmatrix}
\end{align}
$$

$$
\begin{align}
10 \times
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
=
\begin{bmatrix}
10\times1 & 10\times2 \\
10\times3 & 10\times4 \\
\end{bmatrix}
=
\begin{bmatrix}
10 & 20 \\
30 & 40
\end{bmatrix}
\end{align}
$$

In [ ]:
x = np.array([1,2,3])
print(10-x) #[10-1, 10-2, 10-3]
print(10*x)
print(10/x)

In [ ]:
print(x > 1.5) #[1>1.5, 2 >1.5, 3>1.5]
print((x>1) & (x<2))

In [ ]:
y = np.arange(6).reshape(2,3)
r = y + 10

print(r.shape)
r, y > 3

### 벡터 + 벡터 연산

$$
\begin{align}
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
+
\begin{bmatrix}
10 \\
20 \\
30 \\
\end{bmatrix}
=
\begin{bmatrix}
1 + 10 \\
2 + 20 \\
3 + 30 \\
\end{bmatrix}
=
\begin{bmatrix}
11 \\
22 \\
33 \\
\end{bmatrix}
\end{align}
$$

$$
\begin{align}
\begin{bmatrix}
1 \\
2 \\
3 \\
\end{bmatrix}
-
\begin{bmatrix}
10 \\
20 \\
30 \\
\end{bmatrix}
=
\begin{bmatrix}
1 - 10 \\
2 - 20 \\
3 - 30 \\
\end{bmatrix}
=
\begin{bmatrix}
-9 \\
-18 \\
-27 \\
\end{bmatrix}
\end{align}
$$

$$
\begin{align}
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
+
\begin{bmatrix}
10 & 20 \\
30 & 40 \\
\end{bmatrix}
=
\begin{bmatrix}
1+10 & 2+20 \\
3+30 & 4+40
\end{bmatrix}
\end{align}
$$

In [ ]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(6,10).reshape(2,2)

# 사칙연산의 경우 각 index끼리 연산이 된다.
print(a+b)
print(a-b)
print(a*b)
print(a/b)

In [ ]:
# 배열간의 연산
# 피연산자인 배열들의 shape이 동일해야 연산이 가능. (2,2,5) + (2,2,5)

a = np.array([10,20,30])
b = np.array([100, 200, 300])
r = a + b
print(a.shape, b.shape, r.shape)
r

In [131]:
a = np.array([1,2,3])
b = np.array([3,4,5])
a**b

array([  1,  16, 243])

### 4-2. 범용 함수
#### 단항 범용 함수
- 매개변수로 한개의 배열을 받는다.
- 한 배열내의 원소별로 연산

<img src="https://velog.velcdn.com/images/newnew_daddy/post/fa89baf0-554f-4599-82af-27c17b260b61/image.png" width="40%">

In [ ]:
arr = np.array([1, 2, 3, 4])

sqrt_arr = np.sqrt(arr)
exp_arr = np.exp(arr)
log_arr = np.log(arr)
sin_arr = np.sin(arr)
cos_arr = np.cos(arr)

print("Square Root Array:", sqrt_arr)
print("Exponential Array:", exp_arr)
print("Logarithm Array:", log_arr)
print("Sine Array:", sin_arr)
print("Cosine Array:", cos_arr)

#### 이항 범용 함수
- 매개변수로 두개의 배열을 받는다.
- 두 배열의 같은 index 원소별로 연산

<img src="https://velog.velcdn.com/images/newnew_daddy/post/f9617af4-f6ac-44da-a9fd-a979703189ab/image.png" width="40%">

In [137]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

add_arr = np.add(arr1, arr2)
sub_arr = np.subtract(arr1, arr2)
mul_arr = np.multiply(arr1, arr2)
div_arr = np.divide(arr1, arr2)

print(arr1 + arr2)
print("Added Array:", add_arr)
print("Subtracted Array:", sub_arr)
print("Multiplied Array:", mul_arr)
print("Divided Array:", div_arr)

[5 7 9]
Added Array: [5 7 9]
Subtracted Array: [-3 -3 -3]
Multiplied Array: [ 4 10 18]
Divided Array: [0.25 0.4  0.5 ]


In [138]:
# 몫연산
print(np.floor_divide(arr2, arr1), arr2/arr1)
# 나머지연산
print(np.mod(arr2, arr1), arr2%arr1)

[4 2 2] [4.  2.5 2. ]
[0 1 0] [0 1 0]


In [139]:
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[4 5 6]
[1 2 3]


In [140]:
print(np.greater(arr1, arr2))
print(np.less(arr1, arr2))

[False False False]
[ True  True  True]


#### 기술통계함수
- 통계 결과를 계산해 주는 함수들
        
<img src="https://velog.velcdn.com/images/newnew_daddy/post/35351b19-db7d-4915-9e97-49db02655357/image.png" width="40%">

- https://docs.scipy.org/doc/numpy-1.15.1/reference/routines.statistics.html

- Quantile(분위수) -> np.quantile(행렬, 분위수(0~1사이))
    >Quantile이란 주어진 데이터를 동등한 크기로 분할하는 지점을 말합니다. 예를 들어, 시험을 치고 상위 10%에 속하는지를 확인하고 싶다면 점수 데이터를 정렬한 뒤 데이터의 수를 10개의 동등한 크기, 즉 각 그룹이 같은 데이터 수를 보유하도로 분할하면 됩니다.

<img src="https://velog.velcdn.com/images/newnew_daddy/post/cf1af72c-c72a-45d1-b23f-096946755530/image.png" width="40%">

- Percentile(백분위수) -> np.percentile(행렬, 0~100)
    >Percentile은 데이터를 100등분하는 지점을 말합니다. 보통 흔히 상위 몇%라고 말할때 주로 사용하는게 바로 이 percentile입니다.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

sum_val = np.sum(arr)
mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)
var_val = np.var(arr)

print("Sum:", sum_val)
print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)
print("Variance:", var_val)

In [142]:
p = np.random.randint(50, size=10)
p

array([22,  5, 19, 39,  3, 45, 28,  3, 28, 24])

In [145]:
print(np.quantile(p, 0.3))
print(np.std(p)) # 표준편차
print(np.var(p)) # 분산
print(np.argmax(p)) # 최대값 index
print(np.argmin(p)) # 최소값 index
print(np.median(p)) # 중앙값
print(np.quantile(p,0.2))
print(np.percentile(p,25))

14.799999999999997
13.828955130450023
191.24
5
4
23.0
4.6
8.5


### 4-2. 브로드캐스팅
<img src="https://velog.velcdn.com/images/newnew_daddy/post/30555f79-aaf7-46bf-97a4-227d7e34c81a/image.png" width="60%">
<img src="https://velog.velcdn.com/images/newnew_daddy/post/86b08b01-7b78-4a79-ac1e-461166cbf3ea/image.png" width="60%">

- **브로드캐스팅의 개념**
    - 브로드캐스팅은 다른 크기의 배열 간의 연산을 가능하게 합니다.
    - 배열 간의 연산을 수행할 때, 자동으로 적절한 형상으로 맞춰주어 동일한 크기의 배열로 만들어 주는 과정
- **브로드캐스팅 규칙**
    1. 배열의 rank (배열의 차원 수)가 서로 다를 경우, 차원이 더 작은 배열의 앞쪽에 1을 추가합니다.
    2. 배열의 shape (형상)이 맞지 않을 경우, 둘 중 하나의 배열의 shape가 1이면 해당 차원을 늘려서 맞춥니다.
    3. 두 배열의 각 차원에서 크기가 다르고, 그 중 하나가 1도 아니라면, 두 배열은 호환되지 않으며 브로드캐스팅이 불가능합니다.

In [ ]:
# 배열과 스칼라의 덧셈

array = np.array([1, 2, 3])
scalar = 5

result = array + scalar
print(result)  # 출력: [6 7 8]

In [ ]:
# 1차원 배열과 2차원 배열의 덧셈
## 여기서 array_1d는 (1, 3) 형상을 가지고, array_2d는 (2, 3) 형상을 가집니다. array_1d는 자동으로 (2, 3) 형상으로 맞춰져서 계산

array_1d = np.array([1, 2, 3])
array_2d = np.array([[10, 20, 30], [40, 50, 60]])

result = array_2d + array_1d
print(result)

In [ ]:
# 2차원 배열과 1차원 배열의 덧셈
## 여기서 array_2d는 (3, 1) 형상을 가지고, array_1d는 (3,) 형상을 가집니다. array_1d는 (1, 3) 형상으로 변환되어 계산됩니다.

array_2d = np.array([[1], [2], [3]])
array_1d = np.array([10, 20, 30])

result = array_2d + array_1d
print(result)

In [5]:
# 3차원 배열과 2차원 배열의 덧셈
## 여기서 array_3d는 (2, 3, 1) 형상을 가지고, array_2d는 (1, 3) 형상을 가집니다. array_2d는 (2, 3, 3) 형상으로 변환되어 계산됩니다.

array_3d = np.array([[[1], [2], [3]], [[4], [5], [6]]])
array_2d = np.array([[10, 20, 30]])

result = array_3d + array_2d
print(result), print(array_3d.shape, array_2d.shape, result.shape)

[[[11 21 31]
  [12 22 32]
  [13 23 33]]

 [[14 24 34]
  [15 25 35]
  [16 26 36]]]
(2, 3, 1) (1, 3) (2, 3, 3)


(None, None)

In [6]:
arr = np.array([1, 2, 3, 4, 5])
cond = (arr % 2 == 0)
filtered_arr = arr[cond]

print("Conditional Indexing Result:", filtered_arr)

Conditional Indexing Result: [2 4]


## 5. 배열 조작 2

### 5-1. 인덱싱

In [ ]:
## 조건에 따른 인덱싱 1

arr = np.array([1, 2, 3, 4, 5])
bool_idx = arr > 2
filtered_arr = arr[bool_idx]

print("Boolean Indexing Result:", filtered_arr)

In [ ]:
## 조건에 다른 인덱싱 2

arr = np.array([1, 2, 3, 4, 5])
cond = (arr % 2 == 0)
filtered_arr = arr[cond]

print("Conditional Indexing Result:", filtered_arr)


In [ ]:
## 인덱스 배열을 사용한 인덱싱

arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
fancy_indexed_arr = arr[indices]

print("Fancy Indexing Result:", fancy_indexed_arr)


### 5-2. 배열 정렬
- Numpy 배열을 기준에 따라 정렬
  - sort
  - lexsort
  - where
  - searchsorted
  - extract

In [ ]:
## np.sort - 배열을 정렬

array = np.array([3, 1, 2, 5, 4])
sorted_array = np.sort(array)
print("Original array:", array)
print("Sorted array:", sorted_array)

In [48]:
## np.lexsort - 여러 키를 기반으로 배열을 정렬. 키는 마지막 배열부터 첫 번째 배열의 순서로 사용됩니다.

names = ('John', 'John', 'Joe', 'Alice')
ages = (25, 23, 25, 24)

# lexsort는 마지막 키부터 정렬하므로, 이름이 동일할 때 나이를 기준으로 정렬
indices = np.lexsort((ages, names))
sorted_names = np.array(names)[indices]
sorted_ages = np.array(ages)[indices]

print("Names sorted:", sorted_names)
print("Ages sorted:", sorted_ages)

Names sorted: ['Alice' 'Joe' 'John' 'John']
Ages sorted: [24 25 23 25]


In [41]:
## np.where - 조건에 따라 배열의 인덱스나 값을 반환

array = np.array([1, 2, 3, 4, 5])
condition = array > 3

# 조건을 만족하는 요소의 인덱스를 반환
indices = np.where(condition)
print("Indices where array > 3:", indices)

# 조건을 만족하는 요소를 특정 값으로 대체
new_array = np.where(condition, array * 10, array)
print("New array:", new_array)


Indices where array > 3: (array([3, 4], dtype=int64),)
New array: [ 1  2  3 40 50]


In [45]:
## np.searchsorted -  정렬된 배열에 값을 삽입할 위치를 반환

sorted_array = np.array([1, 2, 4, 5, 7])
values_to_insert = np.array([3, 6])

indices = np.searchsorted(sorted_array, values_to_insert)
print("Indices to insert values:", indices)

Indices to insert values: [2 4]


In [47]:
## np.extract - 조건을 만족하는 배열의 요소를 추출

array = np.array([1, 2, 3, 4, 5])
condition = array > 1.5

# 조건을 만족하는 요소를 추출
extracted_elements = np.extract(condition, array)
print("Extracted elements:", extracted_elements)

Extracted elements: [2 3 4 5]


### 5-3. arg로 시작하는 함수들
- 배열에서 특정 조건을 만족하는 요소의 인덱스를 찾거나, 배열의 정렬과 관련된 작업을 수행
  - argmax
  - argmin
  - argsort
  - argwhere
  - argpartition

In [ ]:
## argmax - 배열에서 최대값을 가지는 요소의 인덱스를 반환합니다.

arr = np.array([1, 3, 2, 7, 4])
index = np.argmax(arr)
print(index)

In [ ]:
## argmin - 배열에서 최소값을 가지는 요소의 인덱스를 반환합니다.

arr = np.array([1, 3, 2, 0, 4])
index = np.argmin(arr)
print(index)  # 출력: 3

In [9]:
## argsort - 배열을 오름차순 정렬했을 때 원래 배열의 요소들이 이동한 위치를 나타내는 인덱스를 반환

arr = np.array([3, 1, 2])
indices = np.argsort(arr)
print(indices)  # 출력: [1, 2, 0]

## 내림차순
indices = np.argsort(arr)[::-1]
print(indices)  # 출력: [1, 2, 0]

[1 2 0]
[0 2 1]


In [10]:
## argwhere - 조건을 만족하는 요소들의 인덱스를 반환. 2차원 이상의 배열도 적용 가능

arr = np.array([1, 2, 3, 4, 5])
indices = np.argwhere(arr > 3)
print(indices)  # 출력: [[3], [4]]

[[3]
 [4]]


In [38]:
## np.partition(arr, n) - 배열의 순서에 상관없이 작은 숫자를 n개 뽑아 왼쪽으로 놓겠다.
## argpartition - 배열을 부분 정렬하여 지정된 k번째 요소를 기준으로 작은 값들은 앞쪽에, 큰 값들은 뒤쪽에 배치하고 그 인덱스를 반환

rand = np.random.RandomState(42)
arr = rand.randint(0, 10, (4,7))

print("Origin")
print(arr)
print("partiton")
print(np.partition(arr, 4, axis=1))
print("argpartiton")
print(np.argpartition(arr, 4, axis=1))

Origin
[[6 3 7 4 6 9 2]
 [6 7 4 3 7 7 2]
 [5 4 1 7 5 1 4]
 [0 9 5 8 0 9 2]]
partiton
[[3 2 4 6 6 9 7]
 [2 3 4 6 7 7 7]
 [1 4 1 4 5 5 7]
 [0 0 2 5 8 9 9]]
argpartiton
[[1 6 3 4 0 5 2]
 [6 3 2 0 5 1 4]
 [5 6 2 1 0 4 3]
 [4 0 6 2 3 5 1]]
