## 6. 선형대수

### 6-1. 선형대수 함수
- np.dot()
- np.transpose()
- np.linalg.inv()
- np.linalg.det()
- np.linalg.eig() -> https://6mini.github.io/did%20unknown/2021/08/14/didunk6/

#### 내적연산(dot product)

- `@` 연산자 또는 `numpy.dot(벡터/행렬, 벡터/행렬)`  함수 사용
- 벡터간의 내적
    - 같은 index의 원소끼리 곱한뒤 결과를 모두 더한다.
    - 벡터간의 내적의 결과는 스칼라가 된다.
    - $ x \cdot y $ 또는 $x^T y$로 표현
    - 조건
        - 두 벡터의 차원(원소의개수)가 같아야 한다.
        - 앞의 벡터는 행벡터 뒤의 벡터는 열벡터 이어야 한다.
            - numpy 에서는 vector 끼리 연산시 앞의 벡터는 행벡터로 뒤의 벡터는 열벡터로 인식해 처리한다.

$$
\begin{align}
x =
\begin{bmatrix}
1 \\ 2 \\ 3 \\
\end{bmatrix}
,\;\;\;
y = 
\begin{bmatrix}
4 \\ 5 \\ 6 \\
\end{bmatrix} 
\end{align}
$$

$$
\begin{align}
x^T y = 
\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}
\begin{bmatrix}
4 \\ 5 \\ 6 \\
\end{bmatrix} 
= 1 \times 4 + 2 \times 5 + 3 \times 6 = 32
\end{align}
$$

#### 내적연산의 조건
- 앞 행렬의 행과 뒤 행렬의 열간에 내적을 한다.
- 행렬과 행렬을 내적하면 그 결과는 행렬이 된다.
- 앞 행렬의 열수와 뒤 행렬의 행수가 같아야 한다.
- 내적의 결과의 형태(shape)는 앞행렬의 행수와 뒤 행렬의 열의 형태를 가진다.
    - (3 x 2)와 (2 x 5) = (3 x 5)
    - (1 x 5)와 (5 x 1) = (1 x 1)    

$$
\begin{align}
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
\end{align}
$$

$$
\begin{align}
B = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}
\end{align}
$$

$$
\begin{align}
A\cdot B = \begin{bmatrix} 1\times 1 + 2\times 3 + 3 \times 5 & 1\times 2 + 2\times 4 + 3 \times 6  \\ 4\times 1 + 5\times 3 + 6 \times 5  & 4\times 2 + 5\times 4 + 6 \times 6  \end{bmatrix} = 
\begin{bmatrix} 22 & 28 \\ 49 & 64 \end{bmatrix}
\end{align}
$$

In [129]:
a1 = np.arange(1,13).reshape(3,4)
b1 = np.arange(5,17).reshape(4,3)
c1 = np.arange(6).reshape(3,2)

np.dot(a1,b1), a1@b1

(array([[110, 120, 130],
        [262, 288, 314],
        [414, 456, 498]]),
 array([[110, 120, 130],
        [262, 288, 314],
        [414, 456, 498]]))

In [130]:
np.dot(np.dot(a1,b1),c1), (a1@b1)@c1

(array([[ 760, 1120],
        [1832, 2696],
        [2904, 4272]]),
 array([[ 760, 1120],
        [1832, 2696],
        [2904, 4272]]))

In [58]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print(arr2)
# np.dot(): 두 배열의 내적을 계산합니다.
dot_product = np.dot(arr1, arr2)
print("Dot Product:\n", dot_product)

# np.transpose(): 배열의 전치를 반환합니다.
transposed_arr = np.transpose(arr1)
print("Transposed Array:\n", transposed_arr)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Dot Product:
 [[19 22]
 [43 50]]
Transposed Array:
 [[1 3]
 [2 4]]


In [120]:
from numpy.linalg import inv, det, eig

arr = np.array([[1, 2], [3, 4]])

# np.linalg.inv(): 행렬의 역행렬을 계산합니다.
inverse_arr = inv(arr)
print("Inverse Array:\n", inverse_arr)
print(np.dot(arr, inverse_arr))

# np.linalg.det(): 역행렬이 존재하는지 여부를 확인. 0 -> 역행렬 존재 X / 0이외의 값 -> 역행렬 존재
determinant = det(arr)
print("Determinant:", determinant)
print(det(np.array([[0,0], [0,0]])))

# np.linalg.eig(): 행렬의 고유값과 고유벡터를 계산합니다.
eigenvalues, eigenvectors = eig(arr)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Inverse Array:
 [[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
Determinant: -2.0000000000000004
0.0
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [124]:
arr = np.array([[4, 2], [2, 4]]) # 매트릭스 생성

print(eig(arr)) #Eigenvalue와 Eigenvector

value = eig(arr)[0] #Eigenvalue
vector = eig(arr)[1] #Eigenvector

print('Eigenvalue :', value)
print('Eigenvector :', vector)

EigResult(eigenvalues=array([6., 2.]), eigenvectors=array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))
Eigenvalue : [6. 2.]
Eigenvector : [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [125]:
np.dot(arr, vector)

array([[ 4.24264069, -1.41421356],
       [ 4.24264069,  1.41421356]])

In [118]:
np.array(value).shape, vector.shape

((2,), (2, 2))

In [119]:
np.dot([[6, 0], [0, 2]], arr)

array([[24, 12],
       [ 4,  8]])

## 7. 배열 저장 및 불러오기

### 7-1. 바이너리 파일로 저장/읽기
- **np.save("파일경로", 배열)**
    - 배열을 raw 바이너리 형식으로 저장한다. (압축하지 않은)
    - 파일명에 확장자로 npy를 붙인다. (무조건 붙인다. abc.xxx 해도 abc.xxx.npy 로 저장)
- **np.load("파일경로")**
    - 파일에 저장된 배열을 불러온다.
- **np.savez("파일경로", 이름=배열, 이름=배열, ...)**
    - 여러개의 배열을 저장할 때 사용
    - 파일명에 확장자로 npz가 붙는다.
    - 내부적으로 압축해서 저장한다.
    - load() 함수로 불러오면 저장된 배열목록이 반환 된다. 저장시 지정한 이름을 이용해 조회 

In [1]:
import numpy as np

a = np.array([1, 10, 5, 7, 20])
b = np.ones(shape=(3,3,5))
c = np.random.normal(10, 2, size=(5,10)) #평균:10, 표준편차:2
print(a.shape, b.shape, c.shape)

(5,) (3, 3, 5) (5, 10)


In [2]:
# binary 파일에 배열을 저장
# 한파일에 하나에 배열 - save(경로, 배열)
# 경로: 상대경로(현재 working directory 기준 경로), . : 현재디렉토리, ..: 상위디렉토리
#       절대경로(root 디렉토리부터 전체 경로) - c:\a\b\abc
np.save("data/array_a", a)  #data/array_a.npy
np.save("data/array_b.npy", b)
np.save("data/array.c", c) #data/array.c.npy

In [3]:
# 불러오기(load) - load()
a2 = np.load('data/array_a.npy')
b2 = np.load('data/array_b.npy')
c2 = np.load('data/array.c.npy')

print(a2)
print(b2)
print(c2)

[ 1 10  5  7 20]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[ 8.4130659  11.19543239  9.27530979  8.73957262  9.38621063  8.4025236
  11.40206669  9.36356144  8.28962679 10.6658509 ]
 [ 8.29978192 10.36985003 12.05964706  8.58017066  8.67475366 10.93089608
   4.89577291  8.34300704 12.15502457  8.05734223]
 [10.15104087 10.65426095 10.87755188 11.10479966  7.53393409 10.59446406
   8.98402937  9.90909378 12.44098816  7.63606038]
 [ 7.43167508  8.48621674  8.72959296  8.71454025  8.09317757  9.46519291
   7.72172066 10.63775799  7.9000678   6.50084424]
 [ 8.99801634  9.83348618 10.73740148  7.89461481  8.55618807  9.27896608
  11.93359474  7.42898445  8.42434498  7.20127248]]


In [4]:
# 한파일에 여러개 배열 - savez(경로, 이름1=배열, 이름2=배열, ...)
np.savez("data/array", a=a, b=b, c=c) #data/array.npz

In [5]:
arrays = np.load('data/array.npz')
arrays

NpzFile 'data/array.npz' with keys: a, b, c

In [6]:
# 배열들의 이름들을 조회
arrays.files

['a', 'b', 'c']

In [7]:
# 각 배열을 조회 - index연산자 사용
a3 = arrays['a']
b3 = arrays['b']
c3 = arrays['c']

print(a3)
print(b3)
print(c3)

[ 1 10  5  7 20]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[ 8.4130659  11.19543239  9.27530979  8.73957262  9.38621063  8.4025236
  11.40206669  9.36356144  8.28962679 10.6658509 ]
 [ 8.29978192 10.36985003 12.05964706  8.58017066  8.67475366 10.93089608
   4.89577291  8.34300704 12.15502457  8.05734223]
 [10.15104087 10.65426095 10.87755188 11.10479966  7.53393409 10.59446406
   8.98402937  9.90909378 12.44098816  7.63606038]
 [ 7.43167508  8.48621674  8.72959296  8.71454025  8.09317757  9.46519291
   7.72172066 10.63775799  7.9000678   6.50084424]
 [ 8.99801634  9.83348618 10.73740148  7.89461481  8.55618807  9.27896608
  11.93359474  7.42898445  8.42434498  7.20127248]]


### 7-2. 텍스트 파일로 저장/읽기
- **savetxt("파일경로", 배열 , delimiter='공백')**
  - 텍스트 형태로 저장.
  - 각 원소는 공백을 기준으로 나뉘며 delimiter 속성으로 구분자를 지정할 수 있다. (delimiter생략시 공백)
  - 1차원과 2차원 배열만 저장 가능하다. (3차원 이상은 저장이 안된다.)
- **loadtxt("파일경로" ,dtype=float, comments='', delimiter=공백)**

In [8]:
import numpy as np

# 예제 데이터 생성
arr = np.array([[1.5, 2.3, 3.1], [4.2, 5.8, 6.5]])

print(arr)


[[1.5 2.3 3.1]
 [4.2 5.8 6.5]]


In [10]:
# 데이터를 텍스트 파일로 저장
np.savetxt('data/data.txt', arr, delimiter=',')

In [11]:
# 텍스트 파일에서 데이터 불러오기
loaded_data = np.loadtxt('data/data.txt', delimiter=',')

print(loaded_data)

[[1.5 2.3 3.1]
 [4.2 5.8 6.5]]


In [13]:
# CSV 파일에서 데이터 불러오기

data = "1.5,2.3,3.1\n4.2,5.8,6.5\n"
with open('data.csv', 'w') as file:
    file.write(data)

loaded_data = np.loadtxt('data.csv', delimiter=',')
print(loaded_data)


Data loaded from 'data.csv':\n [[1.5 2.3 3.1]
 [4.2 5.8 6.5]]


In [14]:
# 공백으로 구분된 텍스트 파일에서 데이터 불러오기

data = "1.5 2.3 3.1\n4.2 5.8 6.5\n"
with open('data.txt', 'w') as file:
    file.write(data)

loaded_data = np.loadtxt('data.txt')
print(loaded_data)

[[1.5 2.3 3.1]
 [4.2 5.8 6.5]]


In [16]:
# 주석과 헤더가 있는 파일에서 데이터 불러오기

data = "# This is a comment\n# Another comment\n1.5 2.3 3.1\n4.2 5.8 6.5\n"
with open('data_with_comments.txt', 'w') as file:
    file.write(data)

loaded_data = np.loadtxt('data_with_comments.txt', comments='#')
print(loaded_data)


[[1.5 2.3 3.1]
 [4.2 5.8 6.5]]
